defaults:
  - _self_
  - _base_data_config.yaml   # general, dataset-independent, parameters

_target_: src.datamodules.molecular_dynamics_simulation.MolecularDynamicsSimulationDataModule

chem_config_dir: '/gpfs/share/home/2201111701/Kaiwencheng/dyffusion/src/mol_frame/test.yaml'
indices_file: 'index_wu.npy'

valid_size: 10
test_size: 10
predict_size: 10

multi_horizon: False            # use multiple horizons (e.g. 1,2,3,4,5,6,7,8,9,10)
prediction_horizon: null        # prediction horizon (in days), if null, use the default horizon
num_trajectories: null          # number of trajectories to use (null = all)
